### ISSUE TITLE
User edit - Pokazde validacni error

### ISSUE THREAD

**Issue by rhopp** [KminekMatej/tymy#104]
Jakykoliv edit user infa vyhodi validacni error:
`Validation failing, saving disabled!`
Ulozeni ale presto probehne.

Co je zajimave, ze tento error se zobrazi jenom jednou. 
Napriklad zedituju jmeno - kliknu ulozit - error se zobrazi - odkliknu ho - zedituju neco jineho - kliknu ulozit - error se nezobrazi (error se zobrazi az po uplnem znovunacteni stranky (F5))

Zreprodukovatelne jak na brno.tymy tak dev.tymy.

Screencast: https://youtu.be/UtFblF0bJ3w

**Comment by KminekMatej** [comment]
Problémy v javascriptu
