### ISSUE TITLE
Push notifikace na nové příspěvky v diskuzích

### ISSUE THREAD

**Issue by Konopnik** [KminekMatej/tymy#109]

**Comment by KminekMatej** [comment]
?

**Comment by rhopp** [comment]
Predpokladam, ze ma na mysli push notifikace: https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications

**Comment by KminekMatej** [comment]
Může být

**Comment by KminekMatej** [comment]
Implementovány VAPID push notifikace pro desktop, iOS notifikace pro iPhony (dělá frankie) a FCM notifikace pro android appky, na kterých dělá Jarin z PD
