### ISSUE TITLE
Přiliš velké okraje při vyplňování docházky

### ISSUE THREAD

**Issue by yed** [KminekMatej/tymy#110]
Kdyz vyplňuju docházku, tak okraje vpravo a vlevo jsou zbytečně velké. Kvůli tomu se pak tlačítka u událosí nevejdou na jeden řádek.

URL: https://p7.tymy.cz/v2/udalosti

![screenshot_2018-10-20_11-47-31](https://user-images.githubusercontent.com/383156/47254207-14c16380-d45f-11e8-930a-04d3133a0e55.png)

**Comment by KminekMatej** [comment]
Zkusím nějak přepozicovat

**Comment by KminekMatej** [comment]
![image](https://user-images.githubusercontent.com/16462921/47498856-bfba8e80-d85e-11e8-9da9-fb41b6c3b289.png)

![image](https://user-images.githubusercontent.com/16462921/47498874-d1039b00-d85e-11e8-8401-3f07e5f8f32e.png)
