### ISSUE TITLE
Přejmenovat Události zpět na Docházku

### ISSUE THREAD

**Issue by KminekMatej** [KminekMatej/tymy#113]
Požadavek od Elvíry PD. Docházka lépe koresponduje s původnímy týmy.
Na druhou stranu vzhledem k plánovanému volitelnému zobrazení kalendáře ČALDu by to pak moc nedávalo smysl, neb ten už by nebyl Docházkou.
Zvyknou si lidi na Události, nebo to mám přejmenovat?

**Comment by rhopp** [comment]
Za me jsou `Udalosti` uplne v pohode.

**Comment by KminekMatej** [comment]
Zjistil sem že mě to taky vadí. Přejmenoval sem to na Docházku - pouze tedy v českém langfilu.
Pokud budu zobrazovat kalendář jiný (ČALDu), bude to na nějaké zaškrtávadlo nebo tak a bude tam uvedeno něc jako zobrazit kalendář ČALDu v docházce
