### ISSUE TITLE
Historie zmeny dochazky

### ISSUE THREAD

**Issue by rhopp** [KminekMatej/tymy#123]
Na starych tymech slo u akci v dochazce zobrazit jednotlive zmeny (kdo kdy odklikl ze prijde/neprijde, zmenil svou dochazku, ...). Tohle ve v2 chybi.
![image](https://user-images.githubusercontent.com/1215011/48132289-59d4fa80-e293-11e8-9135-c2883a75a728.png)

**Comment by KminekMatej** [comment]
Jo, to bych tam mohl nějak vytáhnout, myslim že v API to je

**Comment by KminekMatej** [comment]
![image](https://user-images.githubusercontent.com/16462921/51566157-1f432d00-1e94-11e9-9931-5eed97b725bb.png)
Commit cefe573af4a1a969b02fc0a539621f68ab48b35b
