### ISSUE TITLE
Nová událost založená v novém GUI se nezobrazí ve starém GUI

### ISSUE THREAD

**Issue by Konopnik** [KminekMatej/tymy#140]
Ve starém GUI se nová událost nezobrazí v kalendáři.
Při editaci ve starém GUI tam chybí titulek - po jeho vyplnění se událost zobrazí.

![image](https://user-images.githubusercontent.com/22317226/60813606-61d39a00-a194-11e9-968c-0366402aded0.png)

**Comment by KminekMatej** [comment]
Zajímavé, asi řešením bude vyžadovat Title i v nové verzi

**Comment by KminekMatej** [comment]
Jakým způsobem se ti povedlo vytvořit událost bez titulku? V novém gui mi ji to nevytvoří, není-li vyplněn ..

**Comment by Konopnik** [comment]
> Jakým způsobem se ti povedlo vytvořit událost bez titulku? V novém gui mi ji to nevytvoří, není-li vyplněn .. @Konopnik

Prostě to zadám takhle: 
![image](https://user-images.githubusercontent.com/22317226/66409005-3e68f700-e9f0-11e9-85ac-db0660738d24.png)

A v staré, když dám tu událost editovat tak vidím tohle:
![image](https://user-images.githubusercontent.com/22317226/66409054-4f196d00-e9f0-11e9-95fd-d6a77566017a.png)

**Comment by KminekMatej** [comment]
Našel jsem chybu a opravil, na DEV.tymy to už funguje. Na ostré to dám s příštím releasem..
