### ISSUE TITLE
Nově registrovaný a povolený uživatel se může přihlásit pouze v novém UI

### ISSUE THREAD

**Issue by Konopnik** [KminekMatej/tymy#141]
Máme na brno.tymy.cz noveho uzivatele (login filip) a pokud se pokusi prihlasit ve starem UI tak to pise, ze nema prava viz screen:
![image](https://user-images.githubusercontent.com/22317226/61614111-3c01c700-ac63-11e9-87c5-f7f7ce1e2712.png)

V novem UI se lze prihlasit.

**Comment by KminekMatej** [comment]
CHyba v nastavení práv na Brno.tymy.cz
