### ISSUE TITLE
Rozdílný počet přihlášených lidí na trénink vs starém UI vs v novém UI

### ISSUE THREAD

**Issue by Konopnik** [KminekMatej/tymy#147]
![image](https://user-images.githubusercontent.com/22317226/82143218-81226580-9842-11ea-83d3-5926eca8c152.png)

**Comment by Konopnik** [comment]
V novém je 18 lidí, ve starém 20 - 2 holky tam jsou navíc.

**Comment by Konopnik** [comment]
Je to tím, že v novém UI se zobrazují pouze "hráči" a nezobrazují se "členové".

**Comment by KminekMatej** [comment]
Zobrazují se všichni hráči + všichni ostatní kteří vyplnili docházku. Hráči kteří nevyplnili docházku se nezobrazují
