### ISSUE TITLE
API error /discussion/4/html/3

### ISSUE THREAD

**Issue by beeforever** [KminekMatej/tymy#151]
Pri GET dev.tymy.cz/api/discussion/4/html/3
dostavam: 

"<!DOCTYPE html></textarea></script></style></pre></xmp></a></iframe></noembed></noframes></noscript></option></select></template></title></table>\n<html>\n<head>\n\t<meta charset=\"utf-8\">\n\t<meta name=\"robots\" content=\"noindex\">\n\t<meta name=\"generator\" content=\"Tracy by Nette Framework\">\n\n\t<title>Nette\\Database\\UniqueConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &apos;23-4&apos; for key &apos;PRIMARY&apos; #23000</title>\n\t\n\t\n\t\n\t<style class=\"tracy-debug\">\n\t#tracy-bs{font: 9pt/1.5 Verdana,sans-serif;background: white;color: #333;position: absolute;z-index: 20000;left: 0;top: 0;width: 100%;text-align: left}#tracy-bs a{text-decoration: none;color: #328ADC;padding: 2px 4px;margin: -2px -4px}#tracy-bs a+a"...	some

**Comment by KminekMatej** [comment]
Opraveno
