### ISSUE TITLE
rozdil proti staremu API /discussion/4/html/1

### ISSUE THREAD

**Issue by beeforever** [KminekMatej/tymy#152]
v /discussion/4/html/1 se vraci v JSONu updatedById :null, updatedAt: null coz ve starem API nebylo (vracelo to updated hodnoty stejne jako created)

**Comment by KminekMatej** [comment]
Ten JSON response co se vrátí obsahuje 
`updatedById` - ID usera co změnil diskuzi (default NULL)
`updatedAt` - Datum změny diskuze - (default datum vytvoření)
`posts[]->updatedById` - ID usera co změnil konkrétní post diskuze (default NULL)
`posts[]->updatedAt` - Datum změny postu (default NULL)

Vyplnění je zaklíčované na úrovni databáze a mezi novým a starým API se toto nezměnilo.
Jediný rozdíl který vidím je ten, že staré API zobrazí v `posts[]->updatedById` nulu namísto null, což je chyba - správně tam má imho být null - tedy že nikdo post ještě neupravil.

To co popisuješ (namísto updated to vratí created) jsem nenašel, můžeš mi uvést příklad týmu a objektu?

Staré API:
```
{
   "discussion":{
      "id":1,
      "createdById":0,
      "updatedById":1,
      "updatedAt":"2011-02-03T13:51:01.000Z",
      "caption":"kecárna",
      "description":"Zde mohou všichni členové debatovat o týmových záležitostech."
   },
   "posts":[
      {
         "id":2131,
         "discussionId":1,
         "post":"ja uz DG nedavam - rameno",
         "createdById":16,
         "createdAt":"2019-11-01T11:57:25.000Z",
         "updatedById":0,
         "sticky":false,
         "newPost":false,
         "createdAtStr":"1.11.2019 12:57"
      }
   ]
}
```

Nové API:
```
{
   "discussion":{
      "id":1,
      "createdAt":null,
      "createdById":null,
      "updatedById":1,
      "updatedAt":"2011-02-03T14:51:01+01:00",
      "caption":"kecárna",
      "description":"Zde mohou všichni členové debatovat o týmových záležitostech."
   },
   "posts":[
      {
         "id":2131,
         "discussionId":1,
         "post":"ja uz DG nedavam - rameno",
         "createdById":16,
         "createdAt":"2019-11-01T12:57:25+01:00",
         "updatedAt":null,
         "updatedById":null,
         "sticky":false,
         "newPost":false,
         "createdAtStr":"1.11.2019 12:57",
         "updatedAtStr":null
      }
   ]
}
```

**Comment by KminekMatej** [comment]
Nenalezeno
