### ISSUE TITLE
[android] Nelze stahnout udalosti (events)

### ISSUE THREAD

**Issue by PROrock** [KminekMatej/tymy#160]
Na mem Android telefonu v mobilni aplikaci tymy (https://play.google.com/store/apps/details?id=cz.jhavelik.tymy) nelze stahnout udalosti. Sekce Diskuze a Tym/clenove mi funguje.
Muzu dodat vic informaci, pokud je potreba. Verzi aplikaci bych mel mit nejaktualnejsi, protoze jsem si pred chvili stahl poprve do mobilu.
![Screenshot_2022-03-16-11-07-23-956_cz jhavelik tymy](https://user-images.githubusercontent.com/1867058/158566591-717c3ebd-a591-4460-bc39-b74245dec828.jpg)

**Comment by KminekMatej** [comment]
Tato chyba opravena, jednalo se o nedorozumění v komunikaci při stahování událostí. Už by to mělo fungovat. Nejde mi ale z aplikace stáhnout detail události, nicméně server nevrací žádnou chybu na request, tak to proberu s autorem appky a pokud bude potřeba úprava api tymy.cz, otevřu na to nový issue

**Comment by PROrock** [comment]
Supr, aspon o chybu mene :-) Diky :-)
