### ISSUE TITLE
bug: Nejde nastavit poznamka v dochazce

### ISSUE THREAD

**Issue by rhopp** [KminekMatej/tymy#174]
Poznamka k dochazce nejde u eventu (`<tymy_url>/event/xxxxx`) nastavit. Viz screencast: https://www.youtube.com/watch?v=elheDw87870
Note: V mesicnim prehledu (`<tymy_url>/event`) poznamka nastavit jde.

**Comment by KminekMatej** [comment]
Díky za videjko i s těmi Flogging Molly nebo kdo to tam hrál na pozadí :) Chybu opravím a dám vědět

**Comment by KminekMatej** [comment]
Opraveno, hotfixnuto i v aktuální verzi. Tedy není nutné čekat na release, ale je potřeba párkrát Ctrl+F5 pro drop browser cache
