### ISSUE TITLE
Feature request: Radit events v Agende podle data vzestupne

### ISSUE THREAD

**Issue by rhopp** [KminekMatej/tymy#175]
Aktualne jsou events v agende (na strane `<tymy-url>/events`) razene podle data sestupne (a.k.a. prvni event v aktualnim mesici je zobrzeny posledni a posledni event v mesici je zobrazeny prvni)
Mi osobne prijde logictejsi razeni vzestupne. Pokud s tim nesouhlasis, klidne issue zavri ;-)
Dik

**Comment by szczepaf** [comment]
Souhlas s Raxem, nejbližší akce by měla byt rozhodně nahoře. Dik.

**Comment by Konopnik** [comment]
+1

**Comment by KminekMatej** [comment]
Ouky douky

**Comment by KminekMatej** [comment]
Řazení dle startTime ascending - bude v novém releasu
