### ISSUE TITLE
API nevraci UNKNOWN usery v /event/:id

### ISSUE THREAD

**Issue by beeforever** [KminekMatej/tymy#215]
pd.tymy.cz -> /event/3890

nikde nevidim uzivatele, kteri maji status unknown. Stare API tyto usery vracelo.

Web jich zobrazuje 31

**Comment by KminekMatej** [comment]
Statusy jsou Hráč / Člen / Marod / Smazán, žádný unknown neexistuje, nemyslíš spíš hráče co nemají vyplněné pohlaví?

**Comment by KminekMatej** [comment]
Useři co mají nevyplněné pohlaví se v attendance zobrazují (na PD např. event 3981, user 410 Luky), tak to trochu dopřesni

**Comment by beeforever** [comment]
OK, myslim **prestatus** na akce UNKNOWN. 
Vraci se ti jen, co maji vyplneny nejaky prestatus. Pokud ho nemaji, nevrati se v odpovedi.

**Comment by KminekMatej** [comment]
Ok, to už dává smysl. Přidáno, bude po releasu. Ta dummy attendance pak vypadá takto:
```
{
    "userId": 1,
    "eventId": 3981,
    "preStatusId": null,
    "preDescription": null,
    "preUserMod": null,
    "preDatMod": null,
    "postStatusId": null,
    "postDescription": null,
    "postUserMod": null,
    "postDatMod": null,
    "user":
    {
        "id": 1,
        "login": "ADMIN",
        "callName": "Méďa",
        "pictureUrl": "/user_pics/1.png?lastmod=1661890513",
        "gender": "MALE",
        "status": "PLAYER"
    },
    "preStatus": null,
    "postStatus": null
}
```
