### ISSUE TITLE
zobrazeni deleted users

### ISSUE THREAD

**Issue by beeforever** [KminekMatej/tymy#250]
Neni jak zobrazit deleted users

**Comment by KminekMatej** [comment]
Deleted users jsou smazaní fyzicky, nejde je nijak zobrazit

**Comment by beeforever** [comment]
To driv ale v tymech nebylo.
Jen se jim zmenil status na deleted

**Comment by KminekMatej** [comment]
Ano, to je tam cca rok nazpět - dopad GDPR
