### ISSUE TITLE
Přesměrování na požadovanou URL po přihlášení

### ISSUE THREAD

**Issue by czokubik** [KminekMatej/tymy#253]
Bylo by dobré, aby návštěvník konkrétní stránky týmu po překonání přihlašovacího dialogu skončil na původně požadované stránce a ne na landing page týmu. Posílám hráčům reminder pro přihlášení na konkrétné nadcházející akci, např.: https://xxx.tymy.cz/event/###-blah-blah. Navigaci na daný link by to urychlilo.

**Comment by KminekMatej** [comment]
To by asi šlo, zařadím to do roadmapy

**Comment by KminekMatej** [comment]
Done by https://github.com/KminekMatej/tymy/pull/260
Bude k dispozici po releasu v 2.8
