### ISSUE TITLE
Překlad do angličtiny

### ISSUE THREAD

**Issue by KminekMatej** [KminekMatej/tymy#60]

**Comment by KminekMatej** [comment]
Přeložit NEON soubory app/lang/fr/xx.en.neon

**Comment by KminekMatej** [comment]
Nechce se toho někdo ujmout? já tu toho mám celkem dost a tohle může udělat celkem kdokoliv, angličtinu snad na tomhle levelu zvládáme všichni .. @Konopnik @yed @yosarin @rhopp ?

**Comment by rhopp** [comment]
Jsou nejake statistiky kolik lidi pouziva anglictinu? Jestli to ma vubec cenu... Za nas tym muzu rict, ze to cenu moc nema... Ikdyz se sem tam nejaky cizak najde, stejne vsechna komunikace na tymech probiha cesky a nevidim moc smysl v prekladu interface... Smysl by mi to davalo, kdyby existoval nejaky tym, ktery ma vetsinu uzivatelu cizojazycnych, pripadne pouziva anglictinu bezne... A v tom pripade dava smysl takove tymy oslovit s prosbou o preklad.
