### ISSUE TITLE
Na seznamu diskuzí (/v2/diskuze) se nezobrazují badge s počtem nepřečtených zpráv

### ISSUE THREAD

**Issue by YoSarin** [KminekMatej/tymy#95]
Když přejdu na stránku se seznamem diskuzí, nevidím kde je co nového

**Comment by KminekMatej** [comment]
Jo, ty badge jsou jen na seznamu diskuzí na úvodní stránce. Opravim

**Comment by KminekMatej** [comment]
Done: 9a58f57f21454d6b30228e3750283eddd59df306
