### ISSUE TITLE
Udržení session dokud mám otevřené okno v prohlížeči

### ISSUE THREAD

**Issue by Konopnik** [KminekMatej/tymy#96]

**Comment by KminekMatej** [comment]
Hm, teoreticky tam každé asi tři minuty lítá refresh na diskuzi, což by mělo session udržet, ale evidentně neudrží. Mrknu na to.

**Comment by YoSarin** [comment]
Jako doplněk by bylo fajn změnit title okna při odhlášení (alespoň přidat nějakej znak, ať je na první pohled vidět, že jsem venku). Momentálně myslím že jsem přihlášenej a nikdo nic nepíše a přitom jsem jen odhlášenej...

**Comment by KminekMatej** [comment]
Třeba dneska mi vydržela session přes noc, ráno stále přihlášenej...

**Comment by Konopnik** [comment]
Tak mě to tu session taky drží... Asi to byla tehdy nějaká kombinace připojování/odpojování na VPNky v práci.

**Comment by KminekMatej** [comment]
Session problém nepotvrzen, upravil jsem tedy pouze login page title, viz d8491ad7d477d1760f2ab9effe8498e2f3099e3f
