### ISSUE TITLE
Nejde vytvorit poznamku (404)

### ISSUE THREAD

**Issue by rhopp** [KminekMatej/tymy#98]
Ukladani formulare pro vytvoreni nove poznamky nic neudela.
V browser console je videt 404 na:
```
Request URL: https://brno.tymy.cz/v2/nastaveni/poznamky/nova?do=noteCreate
Request Method: POST
Status Code: 404 Not Found
Remote Address: 46.36.36.20:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by KminekMatej** [comment]
Nějak to nedovedu nasimulovat, všude se to tváří mravně. Dovedeš napsat nějaký zaručený postup?

**Comment by rhopp** [comment]
@KminekMatej Hmm... tak dneska pro zmenu poznamka vytvorit jde, ale nejde smazat :-D
Screencast: https://youtu.be/SpdbYR3hYyk

**Comment by rhopp** [comment]
@KminekMatej Tak se mi to podarilo zreprodukovat na dev tymech. Zadne extra kroky pro zreprodukovani. 
Screencast:
https://youtu.be/-mY6-HBFa4Y

**Comment by KminekMatej** [comment]
No jo, někdy bych rád napsal testy natolik rozsáhlé že by pokryly testování pře všech možných nastavení uživatelského oprávnění :).

Problém je v tom že založením poznámky se do POST dat vkládá i údaj o speciální stránce (například zobrazit při přihlášení, loginu apod.) a když poznámku zakládá někdo kdo není admin, ačkoliv se tento údaj pošle prázdný, tak není null a tapi zařve. Commit výše zobrazí chybovou hlášku tapi v aplikaci aby to dávalo smysl a já připravim opravu kdy non-admini nebudou odesílat pole Speciální stránka

**Comment by KminekMatej** [comment]
9e2241382181caf0455689f53a4bbdf9103e7b7d - úprava v2 aby pro uživatele co nemají práva na vytváření speciálních poznámek, zašedla daná políčka. S tím souvisí úprava API, kde bylo špatně podané oprávnění a defakto nikdo non-admin neměl právo zakládat poznámky
